---
title: resume
author: Aum Mhapankar
date: '2019-12-15'
slug: myresume
categories: []
tags: []
description: ''
---
# AUM MHAPANKAR
aummhapankar@gmail.com


EDUCATION								 						
The University of Texas at Austin	Bachelor of Sciences and Arts, Biology, BSA Honors
Health Science Scholars Honors Program
Business Healthcare Certificate
Health Professions Certificate	   Fall 2016 – Spring 2020
	Overall GPA: 3.9022 	
EXPERIENCE	 													
MD Anderson – Clinical Research Finance Intern; Houston, TX          		                                            		     Summer 2019
	Worked with the Clinical Research Finance team to help ensure that clinical research at MD Anderson was funded accurately and allocated institutional funds to specific departmental research projects
	Generated monthly and fiscal year financial reports to track productivity, attended Clinical Research Advisory Committee meetings to observe research presentations and approvals, engaged in healthcare policy from CMS proposed rulings and helped find areas where MD Anderson needed institutional and stockholder input, created summary reports
Dallas Cardiovascular Center – Medical Scribe; Dallas, TX          		                                             Summer 2017 – Fall 2018
	Navigated electronic medical records to access prior notes, formulated concise patient histories, documented physical exams, and captured treatment plans
	Partnered with a cardiologist to help enhance patient experience
The Center for Cancer and Blood Disorders – Medical Scribe; Fort Worth, TX                                                        	     Summer 2017
	Gathered and transcribed patients’ medical information and increased expertise in clinical documentation
	Worked with an oncologist/hematologist to help deliver efficient, high quality patient care
Wentwood Community Center – Pool Manager and Lifeguard; Southlake, TX 			                    Summer 2017
	Managed other lifeguards and ensured that the pool functioned properly by overseeing water quality and chemical levels 
	Monitored pool facility and established patron safety in an outdoor setting
Texas Harris Methodist Hospital - Shadowing Intern; Fort Worth, TX          		                                           	     Summer 2017
	Administered mini-exams to patients to assess mental state
	Shadowed a neurologist and examined the functionality of neurological medical equipment
Parkland Hospital at UT Southwestern - Shadowing Intern; Dallas, TX          		                                           	     Summer 2017
	Observed physical medicine and rehabilitation physician in the hospital and in clinic
The REC – Lifeguard; Grapevine, TX	    							Fall 2015 – Summer 2016
	Guarded recreational pool patrons in an indoor setting
ACADEMIC PROJECTS	 												
Epidermal Cell Fates Research Lab – Research Assistant, Paid Mentor	   	                                  Spring 2017 – Fall 2019
	Mentored incoming students by guiding them through experiment protocols and counseling them on research projects
	Restructured Arabidopsis thaliana genome using CRISPR/Cas9 enzyme to edit the PLC7 gene and analyzed new phenotype
Phelps Lab Research at UT Austin – Research Assistant				          		   Spring 2019 – Fall 2019
	Analyzed Microtus ochrogaster (prarie vole) DNA to determine whether vole sexual fidelity behavior is genetically based
Research on Genetic Basis of Roundworm Social Behavior 		                                                                     Spring 2019                             
	Explored and analyzed social behavior of C. elegans strains with natural variants of genes associated with autism
Temple Community Clinic Consulting Project	               Spring 2019
	Collaborated with clinic to develop surveys for chronic illness, mental health, volunteers, and new and existing patients
Freshman Research Initiative at UT Austin – Undergraduate Researcher	                                            	        Fall 2016 – Fall 2017
	Studied the build-up of drug resistance in Pseudomonas fluorescens and its application on the effectiveness of antibiotics
LEADERSHIP EXPERIENCE AND ACTIVITIES										
St. David’s Medical Center at Austin – Department Lead and Volunteer	        	                                  Spring 2018 – Fall 2019
	Trained incoming Main Information Desk Volunteers as the Lead of that department
	Assisted visitors, patients, and employees with information, directions, and facility locations
	Organized Orthopedic Rehab and ICU floors to make the facility more accessible for nurses and patients
Global Medical Training – Summer 2018 Peru Trip Leader			                                                 Spring 2017 – Fall 2019
	Managed group of 30 students and worked under physician supervision to treat over 800 patients and created Trip Video
	Worked to meet local humanitarian and community needs through volunteering at food drives and Austin Marathon
Health Science Scholars Honors Program – Ambassador				   	                   Spring 2017 – Fall 2019 
	Guided younger students in the program through adjusting to college, selecting courses, and studying for classes
	Helped children investigate science in the Explore UT Organ Exhibit and assisted the set-up of CNS Honors Symposium
Micah 6 Food Pantry – Volunteer	           Fall 2018 – Fall 2019
	Stocked food on shelves and aided the homeless population in selecting nutritious food and navigating the pantry
Operation Kindness – Volunteer	      Spring 2019 – Fall 2019
	Fostered newborn puppies and kittens until they were ready for surgery and adoption
Phi Chi Theta Business Fraternity – Member		                                            		                   Fall 2018 – Spring 2019
	Forged a network of students and peers centered on the foundation of business, professionalism, and philanthropy
	Interacted with children of homeless mothers at SLH Starkids, and planted organic crops at the UT Microfarm
Learning Assistant for Introduction to Chemistry 		      				                   Spring 2018 – Fall 2018
	Facilitated the exploration of various concepts of chemistry and helped foster chemistry students’ problem solving skills
	Developed my skills in facilitating discussion, questioning techniques, leading my peers, and helping others learn 
Alpha Epsilon Delta (AED) Pre-Health Honor Society – Activity Coordinator, Mentor 	     	                        Fall 2017 – Fall 2018
	Coordinated and produced large events such as Banquet, Retreat, Campout, Barge, and Field Day
	Volunteered at food banks and events around Austin, such as Micah 6, SURE Walk, hurricane food drives, and Formula 1
Texas Business Healthcare Association – Member							   Fall 2018 – Spring 2019
	Interacted with and explored the managerial, financial, legal, and consulting aspects of the healthcare industry
Texas THON – Fundraising Team Member		                      		                                                 Fall 2016 – Spring 2018
	Raised funds and awareness for the Children’s Miracle Network at Dell Children’s Medical Center
UT Intramural Basketball – Team Captain                                                                                                         Spring 2017 – Spring 2018
Flags for Heroes – Co-Founder, President, Area Coordinator				   	Fall 2014 – Summer 2017
	Co-founded organization to honor veterans’ sacrifices by planting flags on veteran holidays, 
raised over $500 for organizations that provide aid to wounded veterans
Students Making Impacts Through Love & Empathy (S.M.I.L.E.) – Volunteering Member	    	        Fall 2016 – Fall 2017
	Volunteered with children throughout the Austin area at locations such as Dell Children’s Medical Center
HONORS														
	College Scholar Honors (2 years)						                                    Spring 2018 – Spring 2019
	Phi Kappa Phi Honor Society							                                    Spring 2018 – Spring 2019
	University Honors (6 semesters)   					                                                Fall 2016 –  Spring 2019
	Ralph A. Steiner, M.D. College of Natural Sciences Scholarship                  			                        Fall 2017 – Fall 2018
	Baylor Regional Medical Center at Grapevine Scholarship				                                               Fall 2016
	Carroll Medical Academy Scholarship				                                           			              Fall 2016
	National Merit Finalist										     Summer 2016
	National AP Scholar											     Summer 2016

SKILLS: Excel, Word, RStudio, Sony Vegas Pro, Java, Python, Microsoft Office, Leadership, Project Management, Teamwork
INTERESTS: Basketball, Rock Climbing, Photography, Guitar, Film, Travel, International Cuisine, Tennis, Fitness, Healthcare
*Authorized to work in the United States of America

